# Generated by Django 5.1.6 on 2025-07-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_url', models.URLField()),
                ('brand', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('original_price', models.CharField(max_length=50)),
                ('discounted_price', models.CharField(max_length=50)),
            ],
        ),
    ]
